# Generated by Django 4.2.3 on 2023-08-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userpost_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='image',
        ),
    ]
